import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const directory = path.dirname(fileURLToPath(import.meta.url));
const sources = [
  "locales-en.js",
  "locales-ar.js",
  "locales-fr.js",
  "locales-de.js",
  "i18n.js",
  "crypto-vault.js",
  "deepseek-usage.js",
  "demo-data.js",
  "usage-core.js",
  "refresh-ledger.js",
  "app.js",
];

const parts = [];
for (const source of sources) {
  let contents = await readFile(path.join(directory, source), "utf8");
  if (source === "app.js") {
    const applicationStart = contents.indexOf("const encryptedVault");
    if (applicationStart === -1) throw new Error("Could not find the app entry point.");
    contents = contents.slice(applicationStart);
  }
  parts.push(`\n/* ${source} */\n${contents.replace(/^export\s+/gm, "")}`);
}

const bundle = `/* Generated by npm run build. Edit the source modules, not this file. */\n(() => {\n"use strict";\n${parts.join("\n")}\n})();\n`;
await writeFile(path.join(directory, "app.bundle.js"), bundle, "utf8");
process.stdout.write("Built app.bundle.js\n");
